name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write   # Required for OIDC
  contents: read

jobs:
  # ------------------------------
  # 1. Terraform Infrastructure
  # ------------------------------
  terraform:
    name: Provision Infrastructure
    runs-on: ubuntu-latest

    outputs:
      s3_bucket_name: ${{ steps.tf-output.outputs.s3_bucket_name }}
      lambda_function_name: ${{ steps.tf-output.outputs.lambda_function_name }}
      api_gateway_url: ${{ steps.tf-output.outputs.api_gateway_url }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ACTION_ROLE }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init & Apply
        run: |
          terraform init
          terraform validate
          terraform apply -auto-approve

      - name: Get Terraform Outputs
        id: tf-output
        run: |
          echo "s3_bucket_name=$(terraform output -raw s3_bucket_name)" >> $GITHUB_OUTPUT
          echo "lambda_function_name=$(terraform output -raw lambda_function_name)" >> $GITHUB_OUTPUT
          echo "api_gateway_url=$(terraform output -raw api_gateway_url)" >> $GITHUB_OUTPUT

  # ------------------------------
  # 2. Frontend Deployment
  # ------------------------------
  frontend:
    name: Deploy Frontend (S3)
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ACTION_ROLE }}
          aws-region: us-east-1

      - name: Sync Static Files to S3
        run: |
          BUCKET=${{ needs.terraform.outputs.s3_bucket_name }}
          echo "Syncing frontend files to S3 bucket: $BUCKET"
          aws s3 sync ./s3_files s3://$BUCKET --delete

  # ------------------------------
  # 3. Backend Deployment (Lambda)
  # ------------------------------
  backend:
    name: Deploy Lambda Function
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ACTION_ROLE }}
          aws-region: us-east-1

      - name: Package Lambda
        run: |
          cd lambda
          zip -r ../lambda.zip .
          cd ..

      - name: Update Lambda Code
        run: |
          FUNCTION_NAME=${{ needs.terraform.outputs.lambda_function_name }}
          echo "Updating Lambda function: $FUNCTION_NAME"
          aws lambda update-function-code \
            --function-name $FUNCTION_NAME \
            --zip-file fileb://lambda.zip
